// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btbfkpzydyedzarpsvkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0YmZrcHp5ZHllZHphcnBzdmttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNTczMjgsImV4cCI6MjA3MTczMzMyOH0.OhB6rI939uOk8M1RmaDI0e12WFWJXkYPLbGhCo-urrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});